import express from 'express';
import goalsController from '../controllers/goalsController';

const router = express.Router();

/**
 * @swagger
 * tags:
 *   name: Goals
 *   description: The goals API
 */
/**
 * @swagger
 * components:
 *   schemas:
 *     Goal:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           description: The unique identifier for a goal
 *         student_id:
 *           type: string
 *           description: The ID of the student associated with the goal
 *         generated_by_ai:
 *           type: boolean
 *           description: Whether the goal was generated by AI
 *         goals:
 *           type: array
 *           items:
 *             type: object
 *             properties:
 *               text:
 *                 type: string
 *                 description: The goal description
 *               priority:
 *                 type: string
 *                 description: The priority level of the goal
 *               confidence:
 *                 type: number
 *                 description: Confidence level of AI-generated goal (if applicable)
 *               source:
 *                 type: string
 *                 description: The source of the goal
 *         created_at:
 *           type: string
 *           format: date-time
 *           description: The timestamp when the goal was created
 *       required:
 *         - student_id
 *         - generated_by_ai
 *         - goals
 */
/**
 * @swagger
 * /goals:
 *   post:
 *     summary: Generate goals for a student
 *     tags: [Goals]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               id:
 *                 type: string
 *                 description: The ID of the student for whom goals should be generated
 *     responses:
 *       200:
 *         description: Successfully generated and returned goals
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Goal'
 *       500:
 *         description: Internal server error
 */
router.post('/', goalsController.generateStudentGoals);

export default router;
